local v1 = game:GetService("Players").LocalPlayer.PlayerGui.GardenGuide
local v2 = v1.MainMenu
local v3 = v2.MainMenuFrame
local v4 = v3.GridView
local v5 = v4.GridSFrame
local v6 = v4.CompletionBar
local v7 = v3.DailyQuestView
local v8 = v3.PlayerStatsView
local v9 = v3.AchievementsView
local v10 = v2.TopBar
local v11 = v10.Title
local v12 = v10.Exit
local v13 = v10.Back
local v14 = v2.SideMenu.Main.ButtonHolder
local v15 = v2.FilterSidebar
return {
	["GardenGuideScreen"] = v1,
	["MainMenu"] = v2,
	["MainMenuFrame"] = v3,
	["GridView"] = v4,
	["MenuGrids"] = v5,
	["CompletionBar"] = v6,
	["DailyQuestView"] = v7,
	["PlayerStatsView"] = v8,
	["AchievementsView"] = v9,
	["TopBar"] = v10,
	["TitleLabel"] = v11,
	["ExitFrame"] = v12,
	["BackFrame"] = v13,
	["SideMenuButtons"] = v14,
	["DropDownMenus"] = v15,
	["SortDropDown"] = v15.Main.Sort,
	["SortButton"] = v10.SORT_BUTTON.Main.SENSOR,
	["FilterDropDown"] = v15.Main.Filter,
	["FilterButton"] = v10.FILTER_BUTTON.Main.SENSOR
}