--https://raw.githubusercontent.com/suta007/EfHub/refs/heads/master/GAG/src/loader.luau

loadstring(game:HttpGet("https://raw.githubusercontent.com/suta007/EfHub/refs/heads/master/GAG/src/loader.luau"))()

--https://raw.githubusercontent.com/suta007/EfHub/refs/heads/master/GHZs/src/loader.luau

loadstring(game:HttpGet("https://raw.githubusercontent.com/suta007/EfHub/refs/heads/master/GHZs/src/loader.luau"))()

-- https://github.com/suta007/EfHub/releases/download/GHZs-v0.3/ghzs.lua
loadstring(game:HttpGet("https://github.com/suta007/EfHub/releases/download/GHZs-v0.3/ghzs.lua"))()
