--https://raw.githubusercontent.com/suta007/EfHub/refs/heads/master/GAG/src/loader.luau

loadstring(game:HttpGet("https://raw.githubusercontent.com/suta007/EfHub/refs/heads/master/GAG/src/loader.luau"))()

--https://raw.githubusercontent.com/suta007/EfHub/refs/heads/master/GHZs/src/loader.luau

loadstring(game:HttpGet("https://raw.githubusercontent.com/suta007/EfHub/refs/heads/master/GHZs/src/loader.luau"))()
